apiVersion: v1
kind: Service
metadata:
  name: basketball-court-service
spec:
  selector:
    app: basketball-court-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30390